steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/website-tools/wordpress-image', '.' ]
- id: 'terraform init'
  name: 'hashicorp/terraform:1.0.0'
  script: terraform init
  dir: ./DevOps-Dauphine-TP/cloudbuild-terraform
- id: 'terraform plan'
  name: 'hashicorp/terraform:1.0.0'
  script: terraform plan
  dir: ./DevOps-Dauphine-TP/cloudbuild-terraform
- id: 'terraform apply'
  name: 'hashicorp/terraform:1.0.0'
  script: terraform apply --auto-approve
  dir: ./DevOps-Dauphine-TP/cloudbuild-terraform
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/website-tools/wordpress-image'