steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/website-tools/wordpress-image', '.' ]
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/website-tools/wordpress-image'